name: Bug Report
description: Report a bug in succ
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the details below.

  - type: input
    id: version
    attributes:
      label: succ version
      description: Run `succ --version` to find this
      placeholder: "1.2.64"
    validations:
      required: true

  - type: dropdown
    id: editor
    attributes:
      label: Editor / Client
      options:
        - Claude Code
        - Cursor
        - Windsurf
        - Continue.dev
        - CLI only
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what went wrong
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any relevant error output or logs
      render: shell
